### ISSUE TITLE
takagen99详情页

### ISSUE THREAD

**Issue by yunboxtvj** [zhixc/takagen99-Box-release#1]
电视剧超过80集，进入详情页面会很慢，最少要等5秒。比如说一些动画片，大部分200集,经常卡在详情页面。

**Comment by zhixc** [comment]
接口配置能发一下吗？另外具体说明一下是接口配置的哪个站源的哪个影片引起的这个问题

**Comment by yunboxtvj** [comment]
估计是jar包问题,换了一个不卡
